---


- hosts: all
  become: yes
  tasks:
  
  - name: Update cache and upgrade
    package: 
      update_cache: yes

  - name: Removing postgresql to all servers
    package:
      name: postgresql16-server, postgresql15-server, postgresql14-server
      state: absent

         
