---

- hosts: all
  become: yes
  tasks:
  
  - name: Update cache 
    package:
      update_cache: yes

  - name: Installing postgresql to all servers
    package:
      name: postgresql16-server, postgresql15-server, postgresql14-server
      state: present


  - name: Enable postgresql services
    service:
      name: postgresql-16
      state: started
      enabled: yes

         
